/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as HealthzRouteImport } from "./routes/healthz";
import { Route as ApiIndexRouteImport } from "./routes/api/index";
import { Route as ApiSplatRouteImport } from "./routes/api/$";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthSignInRouteImport } from "./routes/auth/sign-in";
import { Route as AuthSignOutRouteImport } from "./routes/auth/sign-out";
import { Route as CliAuthRouteRouteImport } from "./routes/cli/auth/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as CliAuthIndexRouteImport } from "./routes/cli/auth/index";
import { Route as CliAuthKeysIndexRouteImport } from "./routes/cli/auth/keys/index";
import { Route as DashboardDraftsDraftIdIndexRouteImport } from "./routes/dashboard/drafts/$draftId/index";
import { Route as DashboardDraftsDraftIdActionRouteImport } from "./routes/dashboard/drafts/$draftId/$action";
import { Route as CliAuthKeysKeyIdRevokeRouteImport } from "./routes/cli/auth/keys/$keyId/revoke";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthzRoute = HealthzRouteImport.update({
  id: "/healthz",
  path: "/healthz",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: "/api/",
  path: "/api/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/auth/sign-in",
  path: "/auth/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: "/auth/sign-out",
  path: "/auth/sign-out",
  getParentRoute: () => rootRouteImport,
} as any);
const CliAuthRouteRoute = CliAuthRouteRouteImport.update({
  id: "/cli/auth",
  path: "/cli/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const CliAuthIndexRoute = CliAuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CliAuthRouteRoute,
} as any);
const CliAuthKeysIndexRoute = CliAuthKeysIndexRouteImport.update({
  id: "/keys/",
  path: "/keys/",
  getParentRoute: () => CliAuthRouteRoute,
} as any);
const DashboardDraftsDraftIdIndexRoute =
  DashboardDraftsDraftIdIndexRouteImport.update({
    id: "/drafts/$draftId/",
    path: "/drafts/$draftId/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardDraftsDraftIdActionRoute =
  DashboardDraftsDraftIdActionRouteImport.update({
    id: "/drafts/$draftId/$action",
    path: "/drafts/$draftId/$action",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const CliAuthKeysKeyIdRevokeRoute = CliAuthKeysKeyIdRevokeRouteImport.update({
  id: "/keys/$keyId/revoke",
  path: "/keys/$keyId/revoke",
  getParentRoute: () => CliAuthRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/healthz": typeof HealthzRoute;
  "/cli/auth": typeof CliAuthRouteRouteWithChildren;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-out": typeof AuthSignOutRoute;
  "/api/": typeof ApiIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/cli/auth/": typeof CliAuthIndexRoute;
  "/dashboard/drafts/$draftId/$action": typeof DashboardDraftsDraftIdActionRoute;
  "/cli/auth/keys/": typeof CliAuthKeysIndexRoute;
  "/dashboard/drafts/$draftId/": typeof DashboardDraftsDraftIdIndexRoute;
  "/cli/auth/keys/$keyId/revoke": typeof CliAuthKeysKeyIdRevokeRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/healthz": typeof HealthzRoute;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-out": typeof AuthSignOutRoute;
  "/api": typeof ApiIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/cli/auth": typeof CliAuthIndexRoute;
  "/dashboard/drafts/$draftId/$action": typeof DashboardDraftsDraftIdActionRoute;
  "/cli/auth/keys": typeof CliAuthKeysIndexRoute;
  "/dashboard/drafts/$draftId": typeof DashboardDraftsDraftIdIndexRoute;
  "/cli/auth/keys/$keyId/revoke": typeof CliAuthKeysKeyIdRevokeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/healthz": typeof HealthzRoute;
  "/cli/auth": typeof CliAuthRouteRouteWithChildren;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-out": typeof AuthSignOutRoute;
  "/api/": typeof ApiIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/cli/auth/": typeof CliAuthIndexRoute;
  "/dashboard/drafts/$draftId/$action": typeof DashboardDraftsDraftIdActionRoute;
  "/cli/auth/keys/": typeof CliAuthKeysIndexRoute;
  "/dashboard/drafts/$draftId/": typeof DashboardDraftsDraftIdIndexRoute;
  "/cli/auth/keys/$keyId/revoke": typeof CliAuthKeysKeyIdRevokeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/healthz"
    | "/cli/auth"
    | "/api/$"
    | "/auth/callback"
    | "/auth/sign-in"
    | "/auth/sign-out"
    | "/api/"
    | "/dashboard/"
    | "/cli/auth/"
    | "/dashboard/drafts/$draftId/$action"
    | "/cli/auth/keys/"
    | "/dashboard/drafts/$draftId/"
    | "/cli/auth/keys/$keyId/revoke";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/healthz"
    | "/api/$"
    | "/auth/callback"
    | "/auth/sign-in"
    | "/auth/sign-out"
    | "/api"
    | "/dashboard"
    | "/cli/auth"
    | "/dashboard/drafts/$draftId/$action"
    | "/cli/auth/keys"
    | "/dashboard/drafts/$draftId"
    | "/cli/auth/keys/$keyId/revoke";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/healthz"
    | "/cli/auth"
    | "/api/$"
    | "/auth/callback"
    | "/auth/sign-in"
    | "/auth/sign-out"
    | "/api/"
    | "/dashboard/"
    | "/cli/auth/"
    | "/dashboard/drafts/$draftId/$action"
    | "/cli/auth/keys/"
    | "/dashboard/drafts/$draftId/"
    | "/cli/auth/keys/$keyId/revoke";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  HealthzRoute: typeof HealthzRoute;
  CliAuthRouteRoute: typeof CliAuthRouteRouteWithChildren;
  ApiSplatRoute: typeof ApiSplatRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignOutRoute: typeof AuthSignOutRoute;
  ApiIndexRoute: typeof ApiIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/healthz": {
      id: "/healthz";
      path: "/healthz";
      fullPath: "/healthz";
      preLoaderRoute: typeof HealthzRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/": {
      id: "/api/";
      path: "/api";
      fullPath: "/api/";
      preLoaderRoute: typeof ApiIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/sign-in": {
      id: "/auth/sign-in";
      path: "/auth/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof AuthSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/sign-out": {
      id: "/auth/sign-out";
      path: "/auth/sign-out";
      fullPath: "/auth/sign-out";
      preLoaderRoute: typeof AuthSignOutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cli/auth": {
      id: "/cli/auth";
      path: "/cli/auth";
      fullPath: "/cli/auth";
      preLoaderRoute: typeof CliAuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/cli/auth/": {
      id: "/cli/auth/";
      path: "/";
      fullPath: "/cli/auth/";
      preLoaderRoute: typeof CliAuthIndexRouteImport;
      parentRoute: typeof CliAuthRouteRoute;
    };
    "/cli/auth/keys/": {
      id: "/cli/auth/keys/";
      path: "/keys";
      fullPath: "/cli/auth/keys/";
      preLoaderRoute: typeof CliAuthKeysIndexRouteImport;
      parentRoute: typeof CliAuthRouteRoute;
    };
    "/dashboard/drafts/$draftId/": {
      id: "/dashboard/drafts/$draftId/";
      path: "/drafts/$draftId";
      fullPath: "/dashboard/drafts/$draftId/";
      preLoaderRoute: typeof DashboardDraftsDraftIdIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/drafts/$draftId/$action": {
      id: "/dashboard/drafts/$draftId/$action";
      path: "/drafts/$draftId/$action";
      fullPath: "/dashboard/drafts/$draftId/$action";
      preLoaderRoute: typeof DashboardDraftsDraftIdActionRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/cli/auth/keys/$keyId/revoke": {
      id: "/cli/auth/keys/$keyId/revoke";
      path: "/keys/$keyId/revoke";
      fullPath: "/cli/auth/keys/$keyId/revoke";
      preLoaderRoute: typeof CliAuthKeysKeyIdRevokeRouteImport;
      parentRoute: typeof CliAuthRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardDraftsDraftIdActionRoute: typeof DashboardDraftsDraftIdActionRoute;
  DashboardDraftsDraftIdIndexRoute: typeof DashboardDraftsDraftIdIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDraftsDraftIdActionRoute: DashboardDraftsDraftIdActionRoute,
  DashboardDraftsDraftIdIndexRoute: DashboardDraftsDraftIdIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface CliAuthRouteRouteChildren {
  CliAuthIndexRoute: typeof CliAuthIndexRoute;
  CliAuthKeysIndexRoute: typeof CliAuthKeysIndexRoute;
  CliAuthKeysKeyIdRevokeRoute: typeof CliAuthKeysKeyIdRevokeRoute;
}

const CliAuthRouteRouteChildren: CliAuthRouteRouteChildren = {
  CliAuthIndexRoute: CliAuthIndexRoute,
  CliAuthKeysIndexRoute: CliAuthKeysIndexRoute,
  CliAuthKeysKeyIdRevokeRoute: CliAuthKeysKeyIdRevokeRoute,
};

const CliAuthRouteRouteWithChildren = CliAuthRouteRoute._addFileChildren(
  CliAuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  CliAuthRouteRoute: CliAuthRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  ApiIndexRoute: ApiIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
